version: '2'
services:
  web1:
    image: node:7.9.0
    command: npm start
    working_dir: /usr/src/app
    ports:
      - 3000
    volumes:
      - .:/usr/src/app
    links:
      - redis
    environment:
      DOCKER_NAME: "web1"

  web2:
    image: node:7.9.0
    command: npm start
    working_dir: /usr/src/app
    ports:
      - 3000
    volumes:
      - .:/usr/src/app
    links:
      - redis
    environment:
      DOCKER_NAME: "web2"
  web3:
    image: node:7.9.0
    command: npm start
    working_dir: /usr/src/app
    ports:
      - 3000
    volumes:
      - .:/usr/src/app
    links:
      - redis
    environment:
      DOCKER_NAME: "web3"
  redis:
    image: redis
